from workout_api.workout_api.categorias.models import CategoriaModel
from workout_api.workout_api.centro_treinamento.models import CentroTreinamentoModel
from workout_api.workout_api.atleta.models import AtletaModel